version: "3.7"

services:

    memcached1:
        image: memcached:1.6
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        env_file:
            - common.env
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.hostname == raspberrypi
        networks:
            - backend
        logging:
            driver: journald


networks:

    backend:
        driver: overlay
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 172.21.0.0/16
