version: "3.7"

secrets:
    AUTH_PUBLIC_KEY:
        file: ./auth_public.key
    AUTH_PRIVATE_KEY:
        file: ./auth_private.key


services:

    router:
        image: bayrell/cloud_router:20200426_182005
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "router_data:/data"
            - "../router/root/router.php:/root/router.php"
        secrets:
            - AUTH_PUBLIC_KEY
            - AUTH_PRIVATE_KEY
        env_file:
            - common.env
        environment:
            DNS_RESOLVER: 127.0.0.11
            CLOUD_WEB_PANEL: web_panel
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.role == manager
        networks:
            - frontend
        logging:
            driver: journald

volumes:
    router_data:

networks:

    frontend:
        driver: overlay
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16
