version: "3.7"

secrets:
    AUTH_PUBLIC_KEY:
        file: ./auth_public.key
    AUTH_PRIVATE_KEY:
        file: ./auth_private.key


services:

    web_panel:
        image: bayrell/cloud_web_panel:20200427_120525
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "web_panel_data:/data"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "../src:/var/www"
        secrets:
            - AUTH_PUBLIC_KEY
            - AUTH_PRIVATE_KEY
        env_file:
            - common.env
        environment:
            MEMCACHED: "memcached1"
            MYSQL_HOST: "mysql1"
            MYSQL_USERNAME: "lasto4ka"
            MYSQL_PASSWORD: "7DF&d7jr!Lk5rZ^b"
            MYSQL_DB: "web_panel"
            COOKIE_NAME: auth_token
            COOKIE_EXPIRE: 86400
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.role == manager
        networks:
            - backend
            - frontend
        logging:
            driver: journald

volumes:
    web_panel_data:

networks:

    backend:
        driver: overlay
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 172.21.0.0/16

    frontend:
        driver: overlay
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16
                