version: "3.7"

services:
    
    rabbitmq:
        image: rabbitmq:3.8.9-management
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "rabbitmq_data:/var/lib/rabbitmq"
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - backend
        ports:
          - target: 15672
            published: 15672
            protocol: tcp
            mode: host
        logging:
            driver: journald

volumes:
    rabbitmq_data:

networks:
    
    backend:
        driver: overlay
        attachable: true
