version: "3.7"

services:
    
    standard:
        image: bayrell/cloud_os_standard:0.1.0-20201125_134343
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "standard_data:/data"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "../../config:/data/config"
            - "../../src:/var/www"
        env_file:
            - ./env.conf
        environment:
            MYSQL_DB: "system_panel"
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - backend
        ports:
          - target: 80
            published: 8080
            protocol: tcp
            mode: host
          - target: 22
            published: 8022
            protocol: tcp
            mode: host            
        logging:
            driver: journald

volumes:
    standard_data:

networks:
    
    backend:
        driver: overlay
        attachable: true
