version: "3.7"

services:

    gateway:
        image: bayrell/bus_gateway:0.1.0-20201201_125846
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        env_file:
            - ./env.conf
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - cloud_admin
        logging:
            driver: journald

networks:
    
    cloud_admin:
        external: true
