version: "3.7"

services:
    
    http:
        image: bayrell/load_balancer_http:0.2.0
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "http_data:/data"
        env_file:
            - env.conf
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - cloud_admin
            - load_balancer
        ports:
          - target: 80
            published: 80
            protocol: tcp
            mode: host
        logging:
            driver: journald

volumes:
    http_data:

networks:

    cloud_admin:
        external: true

    load_balancer:
        external: true
